name: Build and deploy website/docs

on:
  push:
    branches:
      - main
      - landing
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout landing page branch
        uses: actions/checkout@v4
        with:
            ref: landing
            fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci
          npm run build
        working-directory: ./

      - name: Store landing page output
        run: |
          mkdir -p /tmp/gh-pages/out
          mv dist/* /tmp/gh-pages/out/

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Generate API docs
        run: |
          source .venv/bin/activate
          sphinx-apidoc -o docs/_sphinx verdict
          cd docs/_sphinx
          make html

      - name: Store API docs output
        run: |
          mkdir -p /tmp/gh-pages/out/docs/api
          mv docs/_sphinx/_build/html/verdict.html docs/_sphinx/_build/html/index.html
          mv docs/_sphinx/_build/html/* /tmp/gh-pages/out/docs/api

      - name: Install Retype
        run: npm install retypeapp --global

      - name: Build Retype docs
        env:
          RETYPE_SECRET: ${{ secrets.RETYPE_SECRET }}
        run: |
          cd docs
          RETYPE_SECRET=$RETYPE_SECRET retype build --verbose

      - name: Store Retype docs output
        run: |
          mkdir -p /tmp/gh-pages/out/docs
          mv docs/.retype/* /tmp/gh-pages/out/docs

      - name: Log directory structure
        run: |
          tree /tmp/gh-pages/out -L 2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/gh-pages/out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
